### ISSUE TITLE
[security] No need to log a merged config.

### ISSUE THREAD

**Issue by Zensey** [microparts/configuration-golang#2]
IMHO there's no need to log a merged config. 
It can rise a security problem due to exposure of  a sensible data, like passwords / addresses.

This issue can be addressed by :
- not logging merged config it at all
- introduction of a new tag for sencible info and then check it and masking sensible data before loging

**Comment by smgladkovskiy** [comment]
Show more info while reading and merging configs for more control without dump all.

@Zensey what do you think about it?
